[package]
name = "parquet-reader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.29.0"
rfd = "0.15.0"
parquet = "53.0.0"
arrow-schema = "53.0.0"
arrow = "53.0.0"
